_wandb:
    value:
        cli_version: 0.23.0
        e:
            gg4zh7t2ew35bynbynpgmg7g02r388t7:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "9663676416"
                args:
                    - --batch_size=16
                    - --command_weight=2
                    - --hidden_dim=256
                    - --learning_rate=1.0059596979276648
                    - --max-epochs=50
                    - --num_heads=8
                    - --num_layers=2
                    - --oversample_factor=3
                    - --wandb-project=gcode-fingerprinting
                    - --weight_decay=0.09280087400670244
                    - --use-augmentation
                    - --use-wandb
                codePath: train_multihead.py
                codePathLocal: train_multihead.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "994662584320"
                        used: "629907312640"
                email: seacuello@uri.edu
                executable: /Users/stepheneacuello/Documents/Documents - Manbir's MacBook Air/ELE 588 Applied Machine Learning/final_project/gcode_fingerprinting/.venv/bin/python
                host: Manbirs-MacBook-Air.local
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/stepheneacuello/Documents/Documents - Manbir's MacBook Air/ELE 588 Applied Machine Learning/final_project/gcode_fingerprinting/train_multihead.py
                python: CPython 3.14.0
                root: /Users/stepheneacuello/Documents/Documents - Manbir's MacBook Air/ELE 588 Applied Machine Learning/final_project/gcode_fingerprinting
                startedAt: "2025-11-20T05:02:39.553424Z"
                writerId: gg4zh7t2ew35bynbynpgmg7g02r388t7
        m: []
        python_version: 3.14.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 16
            "4": 3.14.0
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
batch_size:
    value: 16
command_weight:
    value: 2
grad_clip:
    value: 1
hidden_dim:
    value: 256
label_smoothing:
    value: 0
learning_rate:
    value: 1.0059596979276648
max-epochs:
    value: 50
multi_head:
    value: true
num_heads:
    value: 8
num_layers:
    value: 2
optimizer:
    value: adamw
oversample_factor:
    value: 3
use_augmentation:
    value: true
vocab_size:
    value: 170
wandb-project:
    value: gcode-fingerprinting
weight_decay:
    value: 0.09280087400670244
