_wandb:
    value:
        cli_version: 0.23.0
        e:
            3f2xqsbnkoie9riqt2y5yjuuvek7eq2n:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "7516192768"
                args:
                    - --data-dir
                    - outputs/processed_v2
                    - --vocab-path
                    - data/gcode_vocab_v2.json
                    - --use-augmentation
                    - --max-epochs
                    - "50"
                    - --patience
                    - "10"
                    - --use-wandb
                    - --batch_size=4
                    - --command_weight=4.133087666525092
                    - --hidden_dim=128
                    - --learning_rate=0.0027412586130787244
                    - --num_heads=4
                    - --num_layers=2
                    - --oversample_factor=5
                    - --weight_decay=0.07148035701454038
                codePath: train_multihead.py
                codePathLocal: train_multihead.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "994662584320"
                        used: "654218637312"
                email: seacuello@uri.edu
                executable: /Users/stepheneacuello/Documents/Documents - Manbir's MacBook Air/ELE 588 Applied Machine Learning/final_project/gcode_fingerprinting/.venv/bin/python
                host: 1.154.20.172.s.wireless.uri.edu
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/stepheneacuello/Documents/Documents - Manbir's MacBook Air/ELE 588 Applied Machine Learning/final_project/gcode_fingerprinting/train_multihead.py
                python: CPython 3.14.0
                root: /Users/stepheneacuello/Documents/Documents - Manbir's MacBook Air/ELE 588 Applied Machine Learning/final_project/gcode_fingerprinting
                startedAt: "2025-11-19T21:47:40.970224Z"
                writerId: 3f2xqsbnkoie9riqt2y5yjuuvek7eq2n
        m: []
        python_version: 3.14.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 16
            "4": 3.14.0
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
batch_size:
    value: 4
command_weight:
    value: 4.133087666525092
grad_clip:
    value: 1
hidden_dim:
    value: 128
label_smoothing:
    value: 0
learning_rate:
    value: 0.0027412586130787244
multi_head:
    value: true
num_heads:
    value: 4
num_layers:
    value: 2
optimizer:
    value: adamw
oversample_factor:
    value: 5
use_augmentation:
    value: true
vocab_size:
    value: 170
weight_decay:
    value: 0.07148035701454038
